// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ocsp/ocsp.proto

package ocsp

import (
	fmt "fmt"
	proto1 "github.com/cloudprober/cloudprober/probes/proto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProbeConf struct {
	// Main domain certificate update interval
	CertificateRefreshInterval *int32 `protobuf:"varint,1,opt,name=certificate_refresh_interval,json=certificateRefreshInterval,def=60000" json:"certificate_refresh_interval,omitempty"`
	// Proxy URL, e.g. http://myproxy:3128
	ProxyUrl *string `protobuf:"bytes,2,opt,name=proxy_url,json=proxyUrl" json:"proxy_url,omitempty"`
	// Interval between targets.
	IntervalBetweenTargetsMsec *int32 `protobuf:"varint,98,opt,name=interval_between_targets_msec,json=intervalBetweenTargetsMsec,def=10" json:"interval_between_targets_msec,omitempty"`
	// Requests per probe.
	// Number of OCSP requests per probe. Requests are executed concurrently and
	// each OCSP request contributes to probe results. For example, if you run two
	// requests per probe, "total" counter will be incremented by 2.
	RequestsPerProbe     *int32   `protobuf:"varint,99,opt,name=requests_per_probe,json=requestsPerProbe,def=1" json:"requests_per_probe,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProbeConf) Reset()         { *m = ProbeConf{} }
func (m *ProbeConf) String() string { return proto.CompactTextString(m) }
func (*ProbeConf) ProtoMessage()    {}
func (*ProbeConf) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6c5c913ab05ed9e, []int{0}
}

func (m *ProbeConf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProbeConf.Unmarshal(m, b)
}
func (m *ProbeConf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProbeConf.Marshal(b, m, deterministic)
}
func (m *ProbeConf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProbeConf.Merge(m, src)
}
func (m *ProbeConf) XXX_Size() int {
	return xxx_messageInfo_ProbeConf.Size(m)
}
func (m *ProbeConf) XXX_DiscardUnknown() {
	xxx_messageInfo_ProbeConf.DiscardUnknown(m)
}

var xxx_messageInfo_ProbeConf proto.InternalMessageInfo

const Default_ProbeConf_CertificateRefreshInterval int32 = 60000
const Default_ProbeConf_IntervalBetweenTargetsMsec int32 = 10
const Default_ProbeConf_RequestsPerProbe int32 = 1

func (m *ProbeConf) GetCertificateRefreshInterval() int32 {
	if m != nil && m.CertificateRefreshInterval != nil {
		return *m.CertificateRefreshInterval
	}
	return Default_ProbeConf_CertificateRefreshInterval
}

func (m *ProbeConf) GetProxyUrl() string {
	if m != nil && m.ProxyUrl != nil {
		return *m.ProxyUrl
	}
	return ""
}

func (m *ProbeConf) GetIntervalBetweenTargetsMsec() int32 {
	if m != nil && m.IntervalBetweenTargetsMsec != nil {
		return *m.IntervalBetweenTargetsMsec
	}
	return Default_ProbeConf_IntervalBetweenTargetsMsec
}

func (m *ProbeConf) GetRequestsPerProbe() int32 {
	if m != nil && m.RequestsPerProbe != nil {
		return *m.RequestsPerProbe
	}
	return Default_ProbeConf_RequestsPerProbe
}

var E_OcspProbe = &proto.ExtensionDesc{
	ExtendedType:  (*proto1.ProbeDef)(nil),
	ExtensionType: (*ProbeConf)(nil),
	Field:         200,
	Name:          "ocsp.ocsp_probe",
	Tag:           "bytes,200,opt,name=ocsp_probe",
	Filename:      "ocsp/ocsp.proto",
}

func init() {
	proto.RegisterType((*ProbeConf)(nil), "ocsp.ProbeConf")
	proto.RegisterExtension(E_OcspProbe)
}

func init() { proto.RegisterFile("ocsp/ocsp.proto", fileDescriptor_f6c5c913ab05ed9e) }

var fileDescriptor_f6c5c913ab05ed9e = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xbd, 0x4e, 0xc3, 0x30,
	0x10, 0x80, 0x95, 0x8a, 0x4a, 0xc4, 0x0c, 0x45, 0x9e, 0xa2, 0x50, 0xa4, 0x8a, 0xa9, 0x93, 0x93,
	0x32, 0x30, 0x54, 0x4c, 0xfc, 0x08, 0x31, 0x54, 0xaa, 0x2c, 0x98, 0xad, 0xc4, 0x5c, 0xd2, 0x48,
	0x69, 0x1c, 0xce, 0x0e, 0x3f, 0x6f, 0xc8, 0xab, 0xf0, 0x16, 0xc8, 0x67, 0x82, 0xca, 0x62, 0xdf,
	0xf9, 0xbe, 0x3b, 0xeb, 0x3e, 0x36, 0x33, 0xda, 0xf6, 0x99, 0x3f, 0x44, 0x8f, 0xc6, 0x19, 0x7e,
	0xe4, 0xe3, 0xf4, 0xba, 0x6e, 0xdc, 0x6e, 0x28, 0x85, 0x36, 0xfb, 0x4c, 0xb7, 0x66, 0x78, 0xe9,
	0xd1, 0x94, 0x80, 0xff, 0x62, 0xba, 0x6c, 0x46, 0x6d, 0x99, 0x36, 0x5d, 0xd5, 0xd4, 0x61, 0xc6,
	0xc5, 0x77, 0xc4, 0xe2, 0xad, 0xaf, 0xde, 0x9a, 0xae, 0xe2, 0x0f, 0x6c, 0xae, 0x01, 0x5d, 0x53,
	0x35, 0xba, 0x70, 0xa0, 0x10, 0x2a, 0x04, 0xbb, 0x53, 0x4d, 0xe7, 0x00, 0xdf, 0x8a, 0x36, 0x89,
	0x16, 0xd1, 0x72, 0xba, 0x9e, 0x5e, 0xe5, 0x79, 0x9e, 0xcb, 0xf4, 0x00, 0x95, 0x81, 0x7c, 0xfc,
	0x05, 0xf9, 0x19, 0x8b, 0x7b, 0x34, 0x1f, 0x9f, 0x6a, 0xc0, 0x36, 0x99, 0x2c, 0xa2, 0x65, 0x2c,
	0x8f, 0xe9, 0xe1, 0x19, 0x5b, 0x7e, 0xcf, 0xce, 0xc7, 0x89, 0xaa, 0x04, 0xf7, 0x0e, 0xd0, 0x29,
	0x57, 0x60, 0x0d, 0xce, 0xaa, 0xbd, 0x05, 0x9d, 0x94, 0xf4, 0xcd, 0x64, 0x95, 0xcb, 0x74, 0x04,
	0x6f, 0x02, 0xf7, 0x14, 0xb0, 0x8d, 0x05, 0xcd, 0x33, 0xc6, 0x11, 0x5e, 0x07, 0xb0, 0xce, 0xaa,
	0x1e, 0x50, 0xd1, 0x92, 0x89, 0xa6, 0xde, 0x68, 0x25, 0x4f, 0xc7, 0xe2, 0x16, 0x90, 0x36, 0x5c,
	0x6f, 0x18, 0xf3, 0xc6, 0x02, 0xc8, 0xe7, 0xe2, 0xc0, 0x90, 0x08, 0x86, 0x04, 0x81, 0x77, 0x50,
	0x25, 0x5f, 0x7e, 0xd5, 0x93, 0xcb, 0x99, 0x20, 0xdf, 0x7f, 0x86, 0x64, 0xec, 0x73, 0x4a, 0x7f,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x65, 0xff, 0xfb, 0x39, 0x90, 0x01, 0x00, 0x00,
}
